# This is based on docker-compose.yml.
# The service called workshop contains our API protect Python package,
# and there is an environment variable set to access the API protect backend API.

services:

  crapi-identity:
    container_name: crapi-identity
    image: crapi/crapi-identity:${VERSION:-latest}
    ports:
      - "8080:8080"
    environment:
      - DB_NAME=crapi
      - DB_USER=admin
      - DB_PASSWORD=crapisecretpassword
      - DB_HOST=postgresdb
      - DB_PORT=5432
      - SERVER_PORT=${IDENTITY_SERVER_PORT:-8080}
      - BLOCK_SHELL_INJECTION=false
      - JWT_SECRET=crapi
      - MAILHOG_HOST=mailhog
      - MAILHOG_PORT=1025
      - MAILHOG_DOMAIN=example.com
      - SMTP_HOST=smtp.example.com
      - SMTP_PORT=587
      - SMTP_EMAIL=user@example.com
      - SMTP_PASS=xxxxxxxxxxxxxx
      - SMTP_FROM=no-reply@example.com
      - SMTP_AUTH=true
      - SMTP_STARTTLS=true
    depends_on:
      postgresdb:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    healthcheck:
        test: curl 0.0.0.0:${IDENTITY_SERVER_PORT:-8080}/identity/health_check
        interval: 15s
        timeout: 15s
        retries: 15
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 384M
    restart: unless-stopped

  crapi-community:
    container_name: crapi-community
    image: crapi/crapi-community:${VERSION:-latest}
    ports:
      - "8087:8087"
    environment:
      - DB_NAME=crapi
      - DB_USER=admin
      - DB_PASSWORD=crapisecretpassword
      - DB_HOST=postgresdb
      - DB_PORT=5432
      - SERVER_PORT=${COMMUNITY_SERVER_PORT:-8087}
      - MONGO_DB_HOST=mongodb
      - MONGO_DB_PORT=27017
      - MONGO_DB_USER=admin
      - MONGO_DB_PASSWORD=crapisecretpassword
      - MONGO_DB_NAME=crapi
      - JWT_SECRET=crapi
    depends_on:
      postgresdb:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      crapi-identity:
        condition: service_healthy
    healthcheck:
        test: curl 0.0.0.0:${COMMUNITY_SERVER_PORT:-8087}/community/home
        interval: 15s
        timeout: 15s
        retries: 15
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 128M
    restart: unless-stopped

  crapi-workshop:
    container_name: crapi-workshop
    image: crapi/crapi-workshop:${VERSION:-latest}
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=crapi
      - DB_USER=admin
      - DB_PASSWORD=crapisecretpassword
      - DB_HOST=postgresdb
      - DB_PORT=5432
      - SERVER_PORT=${WORKSHOP_SERVER_PORT:-8000}
      - MONGO_DB_HOST=mongodb
      - MONGO_DB_PORT=27017
      - MONGO_DB_USER=admin
      - MONGO_DB_PASSWORD=crapisecretpassword
      - MONGO_DB_NAME=crapi
      - JWT_SECRET=crapi
      - SECRET_KEY=crapi
      - DT_API_PROTECT_CLIENT_ID=def58df66cc4f4dd6eeffac99151d9fc79e11093172ed0fe5a85833c6f4e52c7
    depends_on:
      postgresdb:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      crapi-identity:
        condition: service_healthy
      crapi-community:
        condition: service_healthy
    healthcheck:
        test: curl 0.0.0.0:${WORKSHOP_SERVER_PORT:-8000}/workshop/health_check/
        interval: 15s
        timeout: 15s
        retries: 15
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 128M
    restart: unless-stopped

  crapi-web:
    container_name: crapi-web
    image: crapi/crapi-web:${VERSION:-latest}
    ports:
      - "80:80"
    environment:
      - COMMUNITY_SERVICE=crapi-community:${COMMUNITY_SERVER_PORT:-8087}
      - IDENTITY_SERVICE=crapi-identity:${IDENTITY_SERVER_PORT:-8080}
      - WORKSHOP_SERVICE=crapi-workshop:${WORKSHOP_SERVER_PORT:-8000}
    depends_on:
      crapi-community:
        condition: service_healthy
      crapi-identity:
        condition: service_healthy
      crapi-workshop:
        condition: service_healthy
    healthcheck:
        test: curl 0.0.0.0:80/web/health
        interval: 15s
        timeout: 15s
        retries: 15
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 128M
    restart: unless-stopped

  postgresdb:
    container_name: postgresdb
    image: 'postgres:14'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: crapisecretpassword
      POSTGRES_DB: crapi
    #ports:
    #  - "127.0.0.1:5432:5432"
    healthcheck:
        test: ["CMD-SHELL", "pg_isready"]
        interval: 15s
        timeout: 15s
        retries: 15
    volumes:
      - postgresql-data:/var/lib/postgresql/data/
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 128M
    restart: unless-stopped

  mongodb:
    container_name: mongodb
    image: 'mongo:4.4'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: crapisecretpassword
    #ports:
    #  - "127.0.0.1:27017:27017"
    healthcheck:
        test: echo 'db.runCommand("ping").ok' | mongo mongodb:27017/test --quiet
        interval: 15s
        timeout: 15s
        retries: 15
        start_period: 20s
    volumes:
      - mongodb-data:/data/db
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 128M
    restart: unless-stopped

  mailhog:
    user: root
    container_name: mailhog
    image: crapi/mailhog:${VERSION:-latest}
    environment:
      MH_MONGO_URI: admin:crapisecretpassword@mongodb:27017
      MH_STORAGE: mongodb
    ports:
    #  - "127.0.0.1:1025:1025" # smtp server
      - "8025:8025" # Mail ui
    healthcheck:
        test: ["CMD", "nc", "-z", "localhost", "8025"]
        interval: 15s
        timeout: 15s
        retries: 15
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 128M
    restart: unless-stopped

volumes:
  mongodb-data:
  postgresql-data:
